eclipse/repairnator

repairnator/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
repairnator/src/main/java/fr/inria/spirals/repairnator/process/step/GatherTestInformation.java
repairnator/src/main/java/fr/inria/spirals/repairnator/process/step/NopolRepair.java

Since some existing Repairnator steps will be useful for Bears, and some parts of them should have to behaviour differently for Bears, it's important to allow that the steps can check if they are running for Repairnator or Bears.

Allowing AbstractStep subclasses to get the launch mode from ProjectInspector instances.

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java

Sometimes the main process is not exited even if the whole pipeline is finished, leading to errors like #131 . The problem should certainly come from non-daemon threads which are still running, blocking the main process. A first PR has been proposed in Nopol to master this issue (see https://github.com/SpoonLabs/nopol/pull/136), but it may not be enough. So I propose to explicitely exit the main process at the end of the pipeline.

Add an explicit exit in the pipeline to avoid main thread to be blocked

---

jtravis/src/test/java/fr/inria/spirals/jtravis/helpers/BuildHelperTest.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestProjectInspector.java

branch name should not be identified by the patched buildid as we do not store it in the mongodb. Instead we should ALWAYS use the buggybuildid.

change the schema of naming librepair-experiments branches

---

repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java

The serialization of detailed data from scanner for Bears was not happening, because the control argument `scanOnly` was not being passed to the scanner. This argument had been used only for this, and the serialization of detailed data from scanner for Bears should happen independently if the launcher is only for scan or not, thus I just removed this argument from scanner.

Fix issue related to the serialization of detailed data from scanner in Bears mode.

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/Utils.java
repairnator/repairnator-core/src/test/java/fr/inria/spirals/repairnator/TestSerializerUtils.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java

_How the scanner has worked when giving an interval of dates to scan builds:_
For both dates, i.e. `lookFrom` and `lookTo`, the scanner has got it at midnight. Thus, if I want to scan only one day, let's say 31/01/1991, I need to enter `lookFrom=31/01/1991` and `lookTo=01/02/1991`, which looks like strange for potential users (aka me). Moreover, despite the fact it is improbable to happen, if a build happened at 01/02/1991 00:00:00, I will get it, even that I wanted builds only from the day 31/01/1991. If I search two intervals, `lookFrom=31/01/1991` and `lookTo=01/02/1991`, and `lookFrom=01/02/1991` and `lookTo=02/02/1991`, in both searches, the scanner will return the same build that happened at 01/02/1991 00:00:00.
_Proposal:_
To make `lookTo` just before midnight. In the example, …

Fix date interval for scanning builds.

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java

The arg `skip-failing` in scanner module is not necessary for Bears. In `ProjectScanner` there is already the variable `targetFailing` to make the things work properly for Bears.
This PR closes the issue #443.

Remove skip-failing arg from scanner

---

repairnator/scripts/launch_repairnator.sh

When running `launch_repairnator.sh`, I got "./launch_repairnator.sh: line 123: syntax error: unexpected end of file". This PR fixes that.

Fix syntax error in launch_repairnator.sh

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java

When running the pipeline module (directly in intelliJ), the execution crashes when it reaches the first step related to maven because `M2_HOME` was not set. Since this is an issue that should be captured at the beginning, I found a bug in the checks when the `Launcher`starts. This PR is supposed to fix that.

Fix LauncherUtils.checkEnvironmentVariable()

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java

The pipeline was not working for Bears when running it from dockerpool. This is due a bug I introduced when I added the arg `projectsToIgnore`. This PR fixes that.

Fix pipeline launcher for Bears

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/CommitFiles.java

This PR intends to fix issue #588.
I run repairnator to REPAIR the build 384520172, which was the build that exposed the bug. The changes work, mainly because I didn't receive an email from GitHub after the branch was generated: https://github.com/fermadeiral/bears-collection-fp/tree/marlon123-spring-api-rest-curso-384520172-20180527-202310
PS: the build is passing in https://github.com/fermadeiral/repairnator/pull/9

Remove ghOauth from created files to push

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/Utils.java
repairnator/repairnator-core/src/test/java/fr/inria/spirals/repairnator/TestUtils.java

This PR intends to fix issue #168.
I thought on two ways to fix the mentioned issue:
1) To try to repair the push url in the push step (last step of the pipeline)
2) To check the correctness of the push url when other variables are also checked (before the pipeline starts)
I took the second way, since the first way might not work depending on how wrong the push url is, and the user of repairnator would know there was a problem at pushing only in the end of the execution.
WDYT?
PS: the build is passing in https://github.com/fermadeiral/repairnator/pull/8

Add check for pushurl arg

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector4Bears.java

This PR changes the format of branch name for Bears. The resulted branches will have the format `<project slug>-<buggy build id>-<fixer build id>`.
The build is passing in https://github.com/fermadeiral/repairnator/pull/17

Change format of branch name for Bears

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/notifier/EndProcessNotifier.java

Attempt at resolving issue #546. 
If I have understood the end of process notification correctly, then the start and end of the repair attempt was already mentioned in the mail. The only thing lacking was the duration, or if duration is not the same as uptime I have made a mistake. Should I perhaps `config.getInstance().getDuration().toString()` instead?

Ready: Improve mail notification for end of process

---

repairnator/docker-images/checkbranches-dockerimage/check_branches.sh

The checkbranches module wasn't working since 3 args can be passed but the script that runs in docker accepted exactly 2 args. This PR fixes that.

Fix checkbranches-dockerimage/check_branches.sh

---

repairnator/repairnator-checkbranches/pom.xml
repairnator/repairnator-checkbranches/src/main/java/fr/inria/spirals/repairnator/checkbranches/Launcher.java
repairnator/repairnator-core/pom.xml
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/docker/DockerHelper.java
repairnator/repairnator-dockerpool/pom.xml
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/AbstractPoolManager.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/Launcher.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/BuildRunner.java

This PR intends to remove duplicate code between `checkbranches/Launcher` and `dockerpool/AbstractPoolManager`. The class `DockerHelper` was added in the core module for that purpose. WDYT?

Add DockerHelper in core module

---

repairnator/docker-images/bears-checkbranches-dockerimage/check_branches.sh

Since the structure of the commits for passing-passing case changed, the check branches for this type of build pair was failing. This PR fixes that.

Fix check branches for Bears for passing-passing case

---

repairnator/repairnator-checkbranches/src/main/java/fr/inria/spirals/repairnator/checkbranches/Launcher.java

`Launcher.docker` was never set, so the docker container was never created/executed and a `NullPointerException` had also happened.

Fix NPE in checkbranches launcher

---

repairnator/docker-images/bears-checkbranches-dockerimage/bears-schema.json
repairnator/docker-images/checkbranches-dockerimage/repairnator-schema.json
resources/bears-schema.json
resources/repairnator-schema.json

It's not always that there exists a failure message for a failed test case, which has been used to set the property "detail" in the json files. This property has been "required" in the json schemas, which makes the "checking branches" to fail on branches that the failed test cases do not have failure message. This PR removes the obligatoriness of this property in the json files.

Remove detail property as required from json schemas

---

repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java

When executing dockerpool, I killed a container and for my surprise, it was serialized as TREATED, which should indicate that the execution of an instance from `RunnablePipelineContainer` was just fine, but in the dockerpool log is possible to see that me killing the container resulted in an exit code different from 0. This PR intends to serialize a `RunnablePipelineContainer` as ERROR instead of TREATED when the container exit code is not 0.

Check if container exit code is really 0 before serializing it as TREATED

---

repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java
repairnator/repairnator-scanner/src/test/java/fr/inria/spirals/repairnator/scanner/ProjectScannerTest.java

The scanner for Bears is bringing a lot of pairs of builds that should not enter for reproduction:
1) when we have a pair of failed and passed builds, it should be checked if the failed build failed in Travis due to test failure;
2) when we have a pair of passed and passed builds, it should be checked if there is one java file between the two builds that is not test file.
This PR fixes that.

Fix scanner for Bears

---

website/repairnator-mongo-rest-api/index.js
website/repairnator-mongo-rest-api/package.json
website/repairnator-mongo-rest-api/yarn.lock

I have updated mongoose to version 5.3 in order to support mongo v 3.6 and higher.
The API is still compatible with the older version of mongodb (3.4). 
Fixes #747

Updated mongoose to 5.3 (issue #747)

---

maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/NPEFixSafeMojo.java
maven-repair/src/test/java/com/github/tdurieux/repair/maven/plugin/NPEFixSafeMojoTest.java

In issue #640 we wish to have a safemode for NPEFix, and since we are currently using maven-repair for the NPEFix, this means we have to make some small changes to maven-repair as well. This PR attempts to make these changes.

Changes to maven-repair to implement a safemode

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/utils/DateUtils.java

Some documents, especially does close to the year shift, had the wrong datestrings, although the correct actual date. This caused weird behaviour in the graph on the dashboard, and this is not how it is supposed to act. 
This PR fixes the format in java that seems to have caused this behaviour.

Fixes wrong character for formating years in strings

---

repairnator/docker-images/pipeline-dockerimage-dev/Dockerfile
repairnator/docker-images/pipeline-dockerimage/Dockerfile

Basic PR to be able to rebuild the docker image, old maven-image is outdated and can not be built.

Updates version of maven base docker-image for the pipeline

---

repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestRTScanner.java

Closes #860 in a way according to the discussion in the aforementioned issue. 
Still need to give travis-ci access to the repairnator organization, but after that there should be no faults.

Change checked out fork in RTScanner test

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/BuildRunner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTLauncher.java

so as to run RtScanner without having to read the documentation

fix: provide sensible default values for RtScanner

---

repairnator/repairnator-core/src/main/java/fr/inria/jtravis/entities/v2/BuildV2.java
repairnator/repairnator-core/src/main/java/fr/inria/jtravis/entities/v2/JobV2.java
repairnator/repairnator-realtime/pom.xml
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/BuildHelperV2.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/FastScanner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/JobHelperv2.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerCollector.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerLearnerScanner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/utils/PatchFilter.java
repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/utils/PatchFilterTest.java

The `SequencerLearnerScanner` class is based on `FastScanner`, but re purposed to fetch passing builds and process them using `SequencerCollector`.
SequencerCollector will be responsible for fetching and scanning all passing builds' commits for compatible [SequenceR](https://github.com/KTH/sequencer) training data.
Passing java builds' commits are being retrieved from GitHub, the current filter checks for:
- Single-file commits
- File to actually be a .java file
- Filter out test files
- Implement filter to only allow single-line fixes.
- filter out patches with several points of modification (scan for multiple `@@` lines)
- scan for pattern `-[line] \n +[line]` and validate that it is not a block change boundary. Use regex(?)
- Deal with data storage and tokenization(?)
- Currently the …

Scan builds' code for SequenceR training data

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorRepair.java

Astor now uses CocoSpoon instead of GZoltar.
Signed-off-by: ginellidavide@gmail.com <ginellidavide@gmail.com>

Changed the fault localization tool used by Astor

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/maven/output/MavenOutputHandler.java

When Repairnator is configured to push the results on an external GitHub repository, the "repairnator.maven.testproject.log" file associated with some builds (e.g., this one: 361311603) contains the GitHub token used by the user. This causes a security problem, GitHub revokes the OAuth token, and thus it is necessary to generate another one every time this situation happens.
The proposed fix replaces the user GitHub Oauth token with the string "CONFIDENTIAL_INFORMATION" before writing it in the .log files.
You can see an example of log file generated with the proposed fix [here](https://github.com/dginelli/test-token-security/blob/tverdokhlebd-mined-in-361311603-20180402-211043/repairnator.maven.testproject.log#L95). The original version of the same file is [this …

fix: does not output GitHub Token in logs

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorRepair.java

Changed the folder names associated with the builds created by Repairnator and Astor in their workspace to avoid conflicts. More details are in the commit messages.

Fix project identifier folders

---

repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerCollector.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerLearnerScanner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/utils/PatchFilter.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/utils/SequencerCollectorHunk.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/utils/SequencerCollectorPatch.java
repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestSequencerCollector.java
repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/utils/PatchFilterTest.java

Single-change hunks are now stored separately to easily tokenize them.
Also disabled commit/push to data repository. If we need to start storing data again it can be enabled. 

feat: Sequencer collector now stores hunks separately

---

doc/repairnator-kubernetes.md
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/PipelineBuildListener.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipelineBuildListener.java

- a plain text with a build id only
- a plain text with a JSON string
- a bytes message with a build id only
- a bytes message with a JSON string
The corresponding test case has been added to this PR. The formats have been documented in `doc/repairnator-kubernetes.md `.
Signed-off-by: Long Zhang <zhanglong3030@qq.com>

feat: PipelineBuildListener handles 4 different message types.

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java

By removing ``printUsage()`` it becomes easier to understand if it's an actual error or a misusage.

refactor: removing printUsage() when an error is found

---

.travis/kubeconfig.skeleton
.travis/travis-deploy.sh

This PR adds the following steps in .travis/travis-deploy.sh to solve #1039 :
- install the latest `kubectl` binary
- setup the kube config, which connects to our K8s cluster
- execute `kubectl` command to delete the current pipeline pods, so that the k8s cluster could recreate new ones using the updated image
The following ENVs need to be setup via Travis configuration:
- K8S_CERTIFICATE_AUTHORITY_DATA
- K8S_CLIENT_KEY_DATA
- K8S_TOKEN
Signed-off-by: Long Zhang <zhanglong3030@qq.com>

feat: continuous deployment on K8S from Travis

---

.travis/travis-deploy.sh

The k8s related commands should be executed at the root folder of the project. This PR fixes the error `cp: cannot stat '.travis/kubeconfig.skeleton': No such file or directory` in travis. (e.g., https://travis-ci.org/eclipse/repairnator/jobs/658817214#L484)
Signed-off-by: Long Zhang <zhanglong3030@qq.com>

fix: a path error when restarting pipeline pods

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/files/FileHelper.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/CommitFiles.java

Repairnator now checks if the `target` folder is ignored or not by Git, and checks if the `.gitignore` file is present or not.
In the first case, if the .`gitignore` file is present, but the `target` folder is not ignored, Repairnator adds these lines to the file:
```
target/
```
In the second case, if the `.gitignore` file is not present, Repairnator creates the file and writes the same content of the first case.
In this way, Repairnator doesn't push the `target` folder to GitHub, avoiding the publication of the GitHub token contained in some files of the folder `target/surefire-reports`.
Signed-off-by: ginellidavide@gmail.com <ginellidavide@gmail.com>

Remove "target" folder from the files to push

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/GitRepositoryLauncherUtils.java

should not be null in outputdir name if no commit hash provided.
Sneaky bug can cause fail in contexts such as in Jenkins.  :)

Fix: should not be null in outputdir name 

---

.travis/travis-run-pipeline.sh
src/repairnator-core/pom.xml

- Previous workaround caused repairnator-core pom files to conflict and fail CD
- It's now consistent with same type of workaround implemented in the [deploy script](https://github.com/eclipse/repairnator/blob/13da69a8d64d05d070bb5a63095f503038ac6181/.travis/travis-deploy.sh#L18)

fix: updated repairnator-pipeline-test dependency workaround

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/SequencerConfig.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
src/repairnator-pipeline/pom.xml
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/SequencerRepair.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/SequencerResult.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/AstorDetectionStrategy.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/DetectionStrategy.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/ModificationPoint.java
src/scripts/config/sequencer.cfg
src/scripts/utils/init_script.sh

Fix Sequencer integration

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/SequencerRepair.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/DockerPipelineRunner.java

- Log containerized pipeline stdout/stderr
- Use named volumes to store containerized pipeline logs and patches
- `DockerPipelineRuner.java` now pulls the docker image name from the config file

refactor: containerized pipeline update

---

src/maven-repair/pom.xml

in order to avoid confusion on Maven central: https://search.maven.org/search?q=repair-maven-plugin

chore: revert groupId change for Maven plugin

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/SequencerRepair.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/AstorDetectionStrategy.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/DetectionStrategy.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/LogParserDetectionStrategy.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/MavenPatchTester.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipelineSequencerRepair.java

- Add differentiated validation functions to SequencerRepair fault detection strategies
- Handle Astor/GZoltar crash, stop pipeline and exit cleanly

refactor: Add differentiated validation functions to SequencerRepair fault detection strategies

---

doc/main-classes.md

Update link after folder rename done in commit https://github.com/eclipse/repairnator/commit/c34c1497fce6fc913694fd3c486ff9ab6a0d63c1

dox: fix link in main-classes.md

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractRepairStep.java
src/repairnator-pipeline/src/main/resources/R-Hero-PR-text.MD

A PR message template for R-Hero patches.
Links still need to be added. You can see a sample [here](https://github.com/javierron/failingProject/pull/4)

Create new R-Hero PR message

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/RepairPatch.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractRepairStep.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/SequencerRepair.java
src/repairnator-pipeline/src/main/resources/R-Hero-PR-text.MD

Here is a working integration of ODS into the R-Hero pipeline.
**Other fixes**
- @SophieHYe @martinezmatias, I changed the directory where ODS saves the buggy-patched file pairs. The path used before was the one provided by the repair tool, and those paths are temporary, and get deleted after the pipeline finishes (at least on SequencerRepair). Any thoughts? Also, I think that this path should be configurable.
- Updated the feedback links on the PR text as URL encoding was not a good idea after all.
- Updated the PR text and title to be +9000 fancy. :tophat:
**Discussion**
Right now this works, but I don't like that I have called the ODS function from within the repair step. Perhaps later we can move overfitting detection to it's own pipeline step? or create a sort of switch in the …

fix: update R-Hero pipeline with ODS

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/SequencerConfig.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/RepairPatch.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/SequencerRepair.java

- Added: write an ODS summary to a file after classification.
- Added: support to store ODS summary and files when running the pipeline in docker mode.

fix: add logging for SequencerRepair-ODS integration

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/RepairPatch.java

In this commit, the ODS return a default label unknown instead of throwing a runtime exception.  Some logs are also added for  debugging.

improve the robust of ODS interface

---

.ci/ci-deploy.sh
.ci/ci-dockerfile
.ci/ci-maven-repair.sh
.ci/ci-run-with-core.sh
.gitignore
src/pom.xml

This fixes #1155 .
See [maven docs](https://maven.apache.org/maven-ci-friendly.html#install-deploy).
Note that this should also eliminate the need for https://github.com/eclipse/repairnator/blob/6c5c1cb01ffe1e3f51d58e608827bce679588181/.travis/travis-run-with-core.sh#L11 during CI.

fix: Maven config transitions from root to child pom files

---

.ci/ci-maven-repair.sh
.ci/ci-run-with-core.sh
Jenkinsfile

- Increase `maven-repair` timeout, as it now includes `repairnator-pipeline` as a dependency.
- Add MAVEN_OPTS do `run-with-core.sh` script.
- Activate https://github.com/jenkinsci/junit-plugin. Closes #1170

chore: improve CI config

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/utils/Pair.java

- Adds default value for localMavenRepository parameter
- Move `Pair` from `maven-repair` to `repairnator-core`. Original class is still included. We need this one to avoid cyclic dependencies between modules.
We need to decide if we keep the original `Pair` class. It is not used anywhere other than NPEFix.

chore: repairnator-core for NPEFix unification

---

Jenkinsfile

Moves junit plugin command to a post action. Fixes commands not being run if stage fails.

chore: fix junit CI plugin config

---

src/repairnator-pipeline/pom.xml

Sorald no longer supports Java 8 (see https://github.com/SpoonLabs/sorald/issues/371
This change is meant to be temporary and be reverted after we drop support for Java 8.

Downgrade Sorald's version so that Repairnator compiles again on Java 8

---

src/repairnator-pipeline/pom.xml
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/components/RunInspector4DefaultGit.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/components/RunInspector4DefaultTravis.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/components/RunInspector4Maven.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfo/GatherTestInformation.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/NPERepair.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/NPERepairSafe.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/testinformation/BugType.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/testinformation/ErrorType.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/testinformation/FailureLocation.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/testinformation/FailureType.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestGatherTestInformation.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNPERepair.java

- Splits `FailureType` into `FailureType` and `ErrorType`
- Adds functionality to `GatherTestInformationStep` about the source classes where the error occurs, the packages where the error occurs and the classes in the stack trace of the error.
Closes #1185

feat; Add source classes information to errors.

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/MavenPatchTester.java

Fix: SequencerRepair: wait for patch to apply before validating it.

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractNPERepairStep.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AssertFixerRepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestAssertFixerRepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestAstorRepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNPERepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNPERepairSafe.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNopolRepair.java

Closes #1194 
- Fixes buggy file path in NPERepair's and AssertFixer's RepairPatches
- Add assertions in repair step tests

fix: save patch on disk for NPERepair and AssertFixer

---

src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/GithubScanner.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerLearnerScanner.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/githubapi/commits/GithubAPICommitAdapter.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestGithubScanner.java

* Changed SequencerCollectorScanner's source to GitHub actions.
* Modified @khaes-kth GitHub scanner to also provide an "only passing" filter.

refactor: SequencerCollectorScanner uses GithubActions instead of TravisCI

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/testinformation/BugType.java

Deflakes `testGatherTestInformationOnlyOneErroring`. Flakyness identified in https://github.com/eclipse/repairnator/issues/1176#issuecomment-809551348

test: Deflakify TestGatherTestInformation

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/SequencerConfig.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/JobStatus.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/RepairPatch.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractNPERepairStep.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractRepairStep.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AssertFixerRepair.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/Sorald.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorRepair.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/nopol/AbstractNopolRepair.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/SequencerRepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipelineArgs.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestGlobalPatchAnalysis.java

Closes #1135
> Why not a separate pipeline step?
Currently repair steps call `recordPatches` when they finish their work, which calls the notifiers. If, after that, we have logic that can filter/rank/etc the patches, it messes up that logic.
> What is there to finish?
Are the patch ranking methods for ODS working (tests are ignored). If so, wouldn't it make more sense to have different modes for the different features? Instead of `OVERFITTING` we would have `ODS_P4J` and `ODS_S4R` for example. @monperrus wdyt?
Also, should ranking be done inside each repair step or overall? The later makes more sense to me, but would require a separate step for it and would mess up the observer pattern mentioned above.
- Add missing parameters to control patch ranking, filtering and classification to …

refactor: Overfitting detection as an AbstractRepairStep component

---

src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipeline.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipelineSequencerRepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipelineb/TestPipelinebGithubMode.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipelineb/TestPipelinebTravisMode.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestGlobalPatchAnalysis.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestProjectInspector.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestBuildProject.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestCloneRepositoryStep.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestGatherTestInformation.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestTestProject.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/TestCheckoutBuggyBuildSourceCode.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/TestCheckoutBuild.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeClasspath.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeModules.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputePlugins.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeSourceDir.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeTestDir.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/push/TestCommitPatch.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/push/TestInitRepoToPush.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestAssertFixerRepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestAstorRepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNPERepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNPERepairSafe.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNopolRepair.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestRTScanner.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/scanner/ProjectScannerTest.java

Waiting for project moves from #1195

refactor: update test projects and build references

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipelineSequencerRepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestGlobalPatchAnalysis.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestProjectInspector4Bears.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/metrics4bears/TestMetrics4BearsJsonFile.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestGatherTestInformation.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestTestProject.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeClasspath.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeTestDir.java
src/repairnator-pipeline/src/test/resources/json-files/bears-386337343-386348522.json
src/repairnator-pipeline/src/test/resources/json-files/repairnator-208897371.json
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestGithubScanner.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestRTScanner.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestZeroScanner.java

- Move tests from external repos to internal repos
- Move test builds from `travis-ci.org` to `travis-ci.com`
- Fixed and reactivated test from `TestMetrics4BearsJsonFile.java`. The other one works locally but fails in CI (see #1219).
- Move https://github.com/henry-lp/SonarQubeRepairTests to internal org and update

refactor: move almost all remaining tests to internal org and reactivate tests

---

doc/main-classes.md

Install instructions didn't include the fact that `repairnator-core` snapshot needs to be locally installed.

Fix install instructions for repairnator-pipeline

---

src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipelineb/TestPipelinebGithubMode.java
src/repairnator-realtime/pom.xml
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/githubapi/commits/GithubAPICommitAdapter.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestGithubScanner.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestRTScanner.java

- Updated GithubScanner tests, as a [change on the GitHub API broke the API library we use and later was fixed.](https://github.com/hub4j/github-api/issues/1156)
- Specified target endpoint on testRepositoryWithoutCheckstyleIsNotInteresting() to avoid flakiness
- Changed target build in testPipelineGitRepositoryAndCommitIdWithFailure() to avoid flakiness  #1176

test: update tests to make CI green again

---

src/maven-repair/pom.xml

closes https://github.com/eclipse/repairnator/issues/1234

chore: remove http://sachaproject.gforge.inria.fr/repositories/releases/

---

doc/README.md
doc/main-classes.md
doc/media.md
doc/repair-tools.md
doc/scripts.md
src/docker-images/pipeline-dockerimage/pipeline_launcher.sh
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/GitRepositoryLauncherUtils.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/TravisLauncherUtils.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/utils/Utils.java
src/repairnator-jenkins-plugin/src/main/java/io/jenkins/plugins/main/RepairnatorProcessBuilder.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/BranchLauncher.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipeline.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipelineBuildListener.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipelineSequencerRepair.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipelineSoraldBot.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipelineb/TestPipelineBuildListenerMainProcess.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipelineb/TestPipelinebGithubMode.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java

Move default travis API to `travis-ci.com`

---

doc/main-classes.md
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/states/LauncherMode.java
src/repairnator-pipeline/pom.xml
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/BranchLauncher.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/MainProcessFactory.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/InspectorFactory.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/JobStatus.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/components/RunInspector4FaultLocalization.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/faultLocalization/FlacocoLocalization.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/PushFaultLocalizationSuggestions.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/soraldbot/SoraldBot.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipelineFaultLocalization.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/faultLocalization/TestFlacocoLocalization.java
src/repairnator-realtime/pom.xml

Repairnator is now able to export fault localization results to a PR review. (See https://github.com/repairnator/failingProject/pull/6).
```bash
java -cp target/repairnator-pipeline-3.3-SNAPSHOT-jar-with-dependencies.jar fr.inria.spirals.repairnator.pipeline.Launcher --launcherMode FAULT_LOCALIZATION --faultLocalization --build 235987498 --ghOauth $GITHUB_TOKEN
```
Opening this draft PR to make sure CI is still working.
TODO:
Closes #1116
Closes #1029

Fault localization mode
