repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherMode.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector4Bears.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/Launcher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/json/JsonSerializer.java

Main changes:
- Reorganization of `ProjectScanner` class;
- Addition of `thereIsDiffOnJavaSourceCode` method to check if there was at least one .java file changed between the build and its previous one (for issue #73);
- Division of `FORBEARS` mode into two modes (`SLUGFORBEARS` and `BUILDFORBEARS`) (for issue #84)---by the way, I think we have to think in other solution here;
- Rename `RepairMode` class to `LauncherMode`.

Towards solving the issues #73 and #84

---

repairnator/Readme.md
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/FileMode.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherMode.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector4Bears.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/Launcher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/json/JsonSerializer.java
scripts/launch_repairnator.sh

I also reorganized the input arguments to follow the same order in the code in the different things (as declaration, initialization, etc) and other small things like that in the `Launcher` class.

Splitting LauncherMode into LauncherMode and FileMode (issue #90)

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/nopol/IgnoreStatus.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/nopol/NopolInformation.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/GatherTestInformation.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/NopolRepair.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/testinformation/FailureLocation.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/testinformation/FailureType.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/gsheet/inspectors/GoogleSpreadSheetNopolSerializer.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestGatherTestInformation.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestNopolRepair.java

Change NopolRepair to now distinguish test errors and failures.

---

jtravis/src/main/java/fr/inria/spirals/jtravis/helpers/BuildHelper.java
jtravis/src/test/java/fr/inria/spirals/jtravis/helpers/BuildHelperTest.java

Fix the bug exposed by @fermadeiral in #106. 
Fix #105

Fix bug when getting previous build on the same branch (issue #105)

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/PushIncriminatedBuild.java
repairnator/scripts/install_git_rebase_last.sh

Should fix bugs #77 #102 #62 #47

Fix push bugs

---

repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/Launcher.java
repairnator/scripts/launch_repairnator.sh
repairnator/scripts/set_env_variable.sh

Add argument for timeout

---

repairnator/dockerImage/Dockerfile
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/BuildToBeInspected.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/Launcher.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/gsheet/inspectors/GoogleSpreadSheetInspectorSerializer.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/gsheet/inspectors/GoogleSpreadSheetInspectorSerializer4Bears.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/gsheet/inspectors/GoogleSpreadSheetNopolSerializer.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestBuildProject.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestCheckoutBuild.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestCloneRepositoryStep.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestComputeClasspath.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestComputeSourceDir.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestGatherTestInformation.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestNopolRepair.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestTestProject.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/gsheet/process/GoogleSpreadSheetScannerDetailedDataSerializer.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/gsheet/process/GoogleSpreadSheetScannerSerializer.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/gsheet/process/GoogleSpreadSheetScannerSerializer4Bears.java
repairnator/scripts/launch_repairnator.sh

Add RunId everywhere to be able to trace what happens

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/AbstractDataSerializer.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorSerializer.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorSerializer4Bears.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/ScannerSerializer4Bears.java

Changes to Fernanda issues

---

repairnator/dockerImage/configure_git.sh
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/maven/MavenHelper.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/SquashRepository.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestSquashRepository.java
travis/install_git_rebase_last.sh
travis/travis-install.sh
travis/travis-run.sh

Fix skip license #182 
Fix another bug with squash: when the first commit is a merge, the rebase can crash the whole process. I added some check to avoid this, in that case the rebase won't work but the process will continue. Added test case. Also change travis to use only one file for git alias.

Fix some issues

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/serializer/Serializer.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/serializer/EndProcessSerializer.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/serializer/TreatedBuildTracking.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorSerializer.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorSerializer4Bears.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorTimeSerializer.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorTimeSerializer4Bears.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/NopolSerializer.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/ScannerDetailedDataSerializer.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/ScannerSerializer.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/ScannerSerializer4Bears.java

Serialize json with date

---

jtravis/src/main/java/fr/inria/spirals/jtravis/helpers/BuildHelper.java
jtravis/src/test/java/fr/inria/spirals/jtravis/helpers/BuildHelperTest.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java

Allow to use bear with failing ids

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector4Bears.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/CheckoutBuild.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/CheckoutPreviousBuild.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/CheckoutPreviousBuildSourceCode.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/CheckoutRepository.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfo/BuildShouldFail.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorSerializer4Bears.java

This way, I can know in a simple way what (build, previous build, previous build on tests of the build) was being analyzed before the pipeline stops.

Adding checkout information on data.

---

bugmetrics/.gitignore
bugmetrics/pom.xml
bugmetrics/src/main/java/JsonParser.java
bugmetrics/src/main/java/Launcher.java

The first three ones are done:
- Number of bugs (-> number of branches in the repo)
- Number of projects with bugs
- Number of exception types

Calculation of overall metrics from json files (issue #250)

---

jtravis/src/main/java/fr/inria/spirals/jtravis/helpers/BuildHelper.java
jtravis/src/test/java/fr/inria/spirals/jtravis/helpers/BuildHelperTest.java

Adding test for GetBuildsFromSlugWithLimitDate() method.
Modification of octal integer called with getDate method.
Changing the name of a method (mistake).

Code test coverage

---

repairnator/repairnator-pipeline/pom.xml
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfo/GatherTestInformation.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestGatherTestInformation.java
travis/travis-install.sh

This PR aims to fix the usage of surefire according to PR https://github.com/apache/maven-surefire/pull/143

Support official version of surefire

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/NopolRepair.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestNopolRepair.java

Add nopol logs

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/notifier/PatchNotifier.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/JobStatus.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/AbstractStep.java

Automatically fork repository when patching

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/AstorRepair.java

Encapsulate astor in a timeout 

---

repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/ScannerDetailedDataSerializer.java

Bug: for both build and previous build, the buggy build was being obtained.

Fix ScannerDetailedDataSerializer.

---

repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/ScannerSerializer4Bears.java

"Look to date" was missing in some parts of ScannerSerializer4Bears.

Fix ScannerSerializer4Bears.

---

repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java

This PR does not contain any bug fix. It's just an extract method refactoring to eliminate duplicate code.

Refactoring in ProjectScanner.

---

repairnator/repairnator-pipeline/pom.xml
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/NopolRepair.java

See https://github.com/SpoonLabs/nopol/issues/156#issuecomment-372133892

Fix nopol version to cede74c7247ab1b6322f32a2665c7974120d6089 Fix #434

---

repairnator/scripts/launch_repairnator.sh

The first two commits are fixes in the script `launch_repairnator.sh`.
The second two commits are only small improvements in the script.

Fixes and improvements in launch_repairnator.sh

---

repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java

Remove docker volume 

---

repairnator/repairnator-checkbranches/src/main/java/fr/inria/spirals/repairnator/checkbranches/Launcher.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfigReader.java
repairnator/repairnator-core/src/test/java/fr/inria/spirals/repairnator/config/TestRepairnatorConfig.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/Launcher.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTLauncher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java

Align RepairnatorConfig with modules' args and use config intensively in all modules

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java

This PR closes the issue #460.

Change help message of the arg workspace in pipeline module.

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/CloneRepository.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestCloneRepositoryStep.java

Also manage the cloning of submodule

---

repairnator/repairnator-checkbranches/src/main/java/fr/inria/spirals/repairnator/checkbranches/Launcher.java
repairnator/repairnator-checkbranches/src/main/java/fr/inria/spirals/repairnator/checkbranches/RunnablePipelineContainer.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/AbstractPoolManager.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/Launcher.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/BuildRunner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/InspectBuilds.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/InspectJobs.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/InspectProcessDuration.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTLauncher.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTScanner.java

This PR contains only refactoring. Most of them are strongly related with config, some directly and some indirectly.
This PR is for issue #471.

Refactoring: clean on fields and parameter passing being possible by the usage of config.

---

repairnator/docker-images/bears-dockerimage/build_repairnator4Bears.sh
repairnator/docker-images/pipeline-dockerimage/build_repairnator.sh

WIP Remove Google Spreadsheet from Repairnator

---

doc/usage.md
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/Launcher.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java
repairnator/scripts/launch_repairnator.sh
repairnator/scripts/repair_buggy_build.sh
repairnator/scripts/set_env_variable.sh

Add switch for bears mode

---

doc/usage.md
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/states/BearsMode.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java
repairnator/scripts/launch_repairnator.sh
repairnator/scripts/launch_scanner.sh
repairnator/scripts/set_env_variable.sh

Add option in scanner for bearsmode

---

repairnator/scripts/set_env_variable.sh
repairnator/scripts/utils/create_structure.sh

The issue this PR addresses was discussed by email. See what you think on the changes.

Change the output and log folder names.

---

repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java

`REPAIR_TOOLS` doesn't exist in Bears docker image.

Fix envValues in RunnablePipelineContainer

---

repairnator/pom.xml
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/InputBuildId.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/Utils.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/AbstractPoolManager.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/serializer/TreatedBuildTracking.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/Metrics.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorSerializer4Bears.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/InspectorTimeSerializer4Bears.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestProjectInspector.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestBuildProject.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestCloneRepositoryStep.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestGatherTestInformation.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestTestProject.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/TestCheckoutBuggyBuildSourceCode.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/TestCheckoutBuild.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeClasspath.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeSourceDir.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeTestDir.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/push/TestCommitPatch.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/push/TestInitRepoToPush.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestAssertFixerRepair.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNPERepair.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNopolRepair.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/InspectBuilds.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTScanner.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/serializer/ScannerDetailedDataSerializer.java
repairnator/repairnator-scanner/src/test/java/fr/inria/spirals/repairnator/scanner/ProjectScannerTest.java

Should fix issues with timeouts and move from int to long the Travis IDs

Upgrade jTravis version

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
repairnator/repairnator-dockerpool/src/main/java/fr/inria/spirals/repairnator/dockerpool/Launcher.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTLauncher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java
repairnator/scripts/config/repairnator.cfg
repairnator/scripts/launch_repairnator.sh
repairnator/scripts/launch_rtscanner.sh
repairnator/scripts/launch_scanner.sh

Now all tools are using an argument for Github Oauth

---

repairnator/scripts/config/repairnator.cfg
repairnator/scripts/launch_dockerpool.sh
repairnator/scripts/reproduce_buggy_and_fixer_builds.sh

This PR adds the script `reproduce_buggy_and_fixer_builds.sh`. This script is brother of `repair_buggy_build.sh`, but for Bears.
This PR also adds the variable `DOCKER_TAG_BEARS` to hold a tag for Bears docker image.
PS: this PR is ready, but it should wait #564 to be merged.

Add reproduce_buggy_and_fixer_builds.sh

---

.travis.yml
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/AbstractStep.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/CommitPatch.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/InitRepoToPush.java

This PR is supposed to fix #574

Fix broken build

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestProjectInspector4Bears.java

Those changes were tested here: https://travis-ci.org/fermadeiral/repairnator/builds/380758157

Fix broken build (now it's true)

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector4Bears.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/AbstractStep.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/AbstractDataSerializer.java

This PR improves the organization of the log generated by the pipeline. No specific log message is added. Instead, 1) when the pipeline is about to start to be executed, it logs the pipeline steps, 2) when a step is going to be executed, it logs the name of the step and its number, 3) when a step is finished, it logs info like the step status, and 4) when the pipeline is ended, it logs the pipeline steps again with their status and execution duration. I believe these changes make more comfortable to read the log and to find stuff about specific steps.
Here is an example on how the log looks like (this log was generated by running the inspector for Bears with passing-passing pair of builds):
```
21:44:55.313 [main] INFO  f.i.s.repairnator.pipeline.Launcher - PIPELINE VERSION: …
```

Improve pipeline log at high level

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/AbstractDataSerializer.java

Fix a bug with status in case of bug during the clone step

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/CommitFiles.java

This PR intends to fix a bug that I introduced when I extracted the method `copyDirectory` in a previous refactoring PR. This bug was also fixed in the PR #584, but that one will take some time to be ready, and I need this fix to test properly other stuff I'm doing now.
Well, if the doc in the method `copyDirectory` is good, I don't need to describe what was the bug. Let's see if I need to update the doc...
PS: the build is passing in https://github.com/fermadeiral/repairnator/pull/7

Fix a bug related to copyDirectory method

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/CheckoutRepository.java

This PR fixes issue #581.
Since you told me that you intend to remove JGit from repairnator, I do not use JGit for the new git commands done in order to reduce work in the future.
PS: the build is passing in https://github.com/fermadeiral/repairnator/pull/10

Fix checkout files in passing/passing case for Bears

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/AbstractStep.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestAbstractStep.java

This PR fixes issue #602.
The build is passing in https://github.com/fermadeiral/repairnator/pull/12

Skip submodules when finding pom.xml

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/git/GitHelperTest.java

This PR fixes issue #601.
The build is passing in https://github.com/fermadeiral/repairnator/pull/13

Compute patch stats only on java files

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/PushProcessEnd.java

This PR fixes issue #605.
The build is passing in https://github.com/fermadeiral/repairnator/pull/14

Fix push for Bears

---

repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestProjectInspector4Bears.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/TestCheckoutBuggyBuildSourceCode.java

The build is passing in https://github.com/fermadeiral/repairnator/pull/16

Fix some tests

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/serializer/SerializerType.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/MetricsSerializer4Bears.java

This PR intends to solve issue #607.
The build is passing in https://github.com/fermadeiral/repairnator/pull/18

Create MetricsSerializer for Bears

---

repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java

This PR fixes a NPE in scanner launcher (I probably introduced that in some refactoring).

Fix NPE in scanner launcher

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/paths/ComputeClasspath.java

This PR intends to remove the "- 2" when getting the number of libraries, which is hard to understand.
The build is passing in https://github.com/fermadeiral/repairnator/pull/22

Small refactoring in ComputeClasspath

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/paths/ComputeSourceDir.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/paths/ComputeTestDir.java

fix: Avoid NPE in ComputeSource/Test dir

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/paths/ComputeClasspath.java

Prevent NPE in ComputeClasspath step

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfo/GatherTestInformation.java

Fix metrics in GatherTestInformation

---

repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeClasspath.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeSourceDir.java

Remove unnecessary execution of pipeline steps from the tests on TestComputeSourceDir and TestComputeClasspath

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/metrics4bears/reproductionBuggyBuild/ProcessDurations.java
repairnator/repairnator-pipeline/src/test/resources/json-files/bears-208897371-backup.json
repairnator/repairnator-pipeline/src/test/resources/json-files/bears-386337343-386348522.json
resources/bears-example-backup.json
resources/bears-schema-backup.json

This PR targets issue #670
Backup files will be used for repairnator.json.

Remove fixing duration from bears.json

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/JobStatus.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/AbstractStep.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestProjectInspector.java

Skip final steps in the case of pipeline being stopped without bug reproduction

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/checkoutrepository/CheckoutRepository.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestCloneRepositoryStep.java

Update the test and fix a bug about getting submodules when checking out

---

.travis/travis-run.sh
repairnator/repairnator-pipeline/pom.xml

Write version ini on travis only

---

repairnator/repairnator-pipeline/pom.xml
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorJGenProgRepair.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorJKaliRepair.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorJMutRepair.java

Upgrade Nopol and Astor

---

repairnator/docker-images/bears-checkbranches-dockerimage/Dockerfile
repairnator/docker-images/bears-checkbranches-dockerimage/check_branches.sh
repairnator/repairnator-checkbranches/src/main/java/fr/inria/spirals/repairnator/checkbranches/Launcher.java
repairnator/repairnator-checkbranches/src/main/java/fr/inria/spirals/repairnator/checkbranches/RunnablePipelineContainer.java
repairnator/scripts/check_branches.sh
repairnator/scripts/config/repairnator.cfg

This PR adds checkbranches docker image for Bears and also starts to make difference when the checkbranches module has been launched for Repairnator or for Bears.

Add checkbranches docker image for Bears

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/AbstractStep.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/CloneRepository.java

Do you think this solve the fixme?

Fix fixme in CloneRepository

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/Utils.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/git/GitHelper.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/paths/TestComputeSourceDir.java

Remove bad test (the build's commit can't be reached anymore due to branch deletion)

---

website/repairnator-mongo-rest-api/package.json
website/repairnator-mongo-rest-api/server/controllers/inspector.controller.js
website/repairnator-mongo-rest-api/server/models/inspector.model.js
website/repairnator-mongo-rest-api/server/routes/index.route.js
website/repairnator-mongo-rest-api/server/routes/inspector.route.js
website/repairnator-mongo-rest-api/server/tests/inspector.test.js
website/repairnator-mongo-rest-api/server/tests/pipeline-error.test.js
website/repairnator-mongo-rest-api/yarn.lock

/inspectors/status/:status is now replaced by a filter /inspectors?status=:status

Replaced /inspectors/status/:status with /inspectors/search + Fix some typo

---

website/repairnator-site/app/index.html
website/repairnator-site/app/scripts/realtime_values.js

The realtime table is now rendered with vue.js.
And we are also able to navigate through old inspectors.

vueified realtime table + add pages

---

website/repairnator-site/app/components/grid.js
website/repairnator-site/app/components/pagination.js
website/repairnator-site/app/index.html
website/repairnator-site/app/scripts/realtime_values.js
website/repairnator-site/gulpfile.js

I put the vue components into a component folder.
I will make both the html and the js more readable. 
All the components will be added in a component.js file that will be loaded before the scripts.

[website] Put the components into a proper component folder

---

website/repairnator-mongo-rest-api/README.md
website/repairnator-mongo-rest-api/server/controllers/patch.controller.js
website/repairnator-mongo-rest-api/server/models/patch.model.js
website/repairnator-mongo-rest-api/server/routes/index.route.js
website/repairnator-mongo-rest-api/server/routes/patch.route.js
website/repairnator-mongo-rest-api/server/tests/patch.test.js
website/repairnator-site/app/index.html
website/repairnator-site/app/scripts/realtime_values.js

In order to do so I have add 3 routes in the api :
- /patches
- /patches/:patchId
- /patches/builds/:buildId
I have also updated the website to add the modal.

Add a patch modal to visualize the patches

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/PatchesSerializer.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/serializer/ToolDiagnosticSerializer.java

This PR seeks to resolve #789.

Make 'date' and 'dateStr' consistent in serializers 

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTLauncher.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTScanner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/notifier/TimedSummaryNotifier.java
repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/notifier/TestTimedSummaryNotifier.java
repairnator/scripts/config/repairnator.cfg
repairnator/scripts/launch_rtscanner.sh

This PR seeks to resolve #734.

Summary emails

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/notifier/PatchNotifier.java

Change the prefix in patch email notifications.

---

maven-repair/.gitignore
maven-repair/.travis-settings.xml
maven-repair/.travis.yml
maven-repair/README.md
maven-repair/pom.xml
maven-repair/src/README.md
maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/AbstractRepairMojo.java
maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/AstorContext.java
maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/CardumenMojo.java
maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/GenProgMojo.java
maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/KaliMojo.java
maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/NPEFixMojo.java
maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/NopolMojo.java
maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/Pair.java
maven-repair/src/pom.xml
maven-repair/src/test/java/com/github/tdurieux/repair/maven/plugin/AstorMojoTest.java
maven-repair/src/test/java/com/github/tdurieux/repair/maven/plugin/BetterAbstractMojoTestCase.java
maven-repair/src/test/java/com/github/tdurieux/repair/maven/plugin/NPEfixMojoTest.java
maven-repair/src/test/java/com/github/tdurieux/repair/maven/plugin/NopolMojoTest.java
maven-repair/src/test/resources/projects/example1/pom.xml
maven-repair/src/test/resources/projects/example1/src/main/java/nopol_examples/nopol_example_1/NopolExample.java
maven-repair/src/test/resources/projects/example1/src/test/java/nopol_examples/nopol_example_1/NopolExampleTest.java
maven-repair/src/test/resources/projects/example2/pom.xml
maven-repair/src/test/resources/projects/example2/src/main/java/Coneflower.java
maven-repair/src/test/resources/projects/example2/src/test/java/ConeflowerTest.java
maven-repair/src/test/resources/projects/example3/pom.xml
maven-repair/src/test/resources/projects/example3/src/main/java/introclassJava/median_3b2376ab_003.java
maven-repair/src/test/resources/projects/example3/src/test/java/introclassJava/median_3b2376ab_003BlackboxTest.java
maven-repair/src/test/resources/projects/example3/src/test/java/introclassJava/median_3b2376ab_003WhiteboxTest.java

It was accidentally removed previously.

Adds the maven-repair project to the repo

---

maven-repair/pom.xml
maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/NPEFixMojo.java

Gave internal call to the Json Object and got output on the Console.
Fix #827

Fix output patch on console for NPEFix

---

doc/scripts.md

I've added some example queries for some data that might be interesting to the [scripts.md](https://github.com/Spirals-Team/repairnator/blob/master/doc/scripts.md) file.

Added queries for some general infor to scripts.md

---

doc/options-configuration-tips.md
repairnator/scripts/patched_builds.py

Changes the patched_builds script to print out all patches into a html format. Also adds some documentation and more interestingly some xpath specifications to get some interesting data.

add query scripts

---

repairnator/repairnator-realtime/pom.xml
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/ActiveMQPipelineRunner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/PipelineRunner.java

In issue (#813) . This PR aims to completes the following tasks :) .
* Add interface PipelineRunner for ActiveMQPipelineRunner to implements
* Implement ActiveMQPipelineRunner

Feat: implement ActiveMQPipelineRunner

---

.travis/travis-before.sh
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/ActiveMQPipelineRunner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/InspectBuilds.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/InspectProcessDuration.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/NopeRunner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTLauncher.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTScanner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/counter/PatchCounter.java
repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestRTScanner.java

This PR add NopeRunner as an implementation of PipelineRunner without docker. Also, This add the new config variables (kubernetesmode, ActiveMQUrl/QueueName) for RTScanner to use when running on kubernetes mode :) .

Feat: add NopeRunner to RT, kubernetesmode option, Add testcase for ActiveMQPipelineRunner.

---

repairnator/repairnator-core/pom.xml
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/PipelineListener.java

Reverts Spirals-Team/repairnator#904

Revert "Feat: add PipelineListener interface"

---

repairnator/docker-images/pipeline-dockerimage/Dockerfile

fix https://travis-ci.org/Spirals-Team/repairnator/builds/566554002

fix deployment

---

repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/DockerPipelineRunner.java

the executor service has its own waiting list, no need to duplicate.

Refactor docker waiting list

---

repairnator/kubernetes-support/README.md
repairnator/kubernetes-support/queue-for-buildids/activemq.yaml
repairnator/kubernetes-support/queue-for-buildids/publisher.py
repairnator/kubernetes-support/repairnator-deployment-yamlfiles/repairnator-pipeline.yaml

Original PR (#878) . Containing the very basic of k8s repairnator :).

Feat: K8s repairnator issue 813 

---

repairnator/build-rainer/pom.xml
repairnator/build-rainer/src/main/java/fr/inria/repairnator/ActiveMQBuildSubmitter.java
repairnator/build-rainer/src/main/java/fr/inria/repairnator/BuildRainer.java
repairnator/build-rainer/src/main/java/fr/inria/repairnator/BuildSubmitter.java
repairnator/build-rainer/src/test/java/fr/inria/repairnator/BuildRainerTest.java
repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestRTScanner.java

Hi :) @monperrus @gluckzhang, ready for reviews.

Feat: Build-Rainer add ActiveMQ component to submit builds

---

repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/Listener.java
repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/ActiveMQPipelineRunner.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTLauncher.java
repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestRTScanner.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/NoopListener.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ProjectScanner.java
repairnator/repairnator-scanner/src/main/java/fr/inria/spirals/repairnator/scanner/ScannerBuildListener.java

Hi @monperrus @gluckzhang :), final part of the K8s scanner implementation. Awaiting for comments.

Feat: JSAP options, kubernetesProcess for launcher

---

repairnator/kubernetes-support/queue-for-buildids/activemq.yaml

@monperrus @gluckzhang hi :) , related to this PR #929 .

Feat: change to an image supporting jmx

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/PipelineBuildListener.java

Hi @monperrus :) , implementation for the pipeline . After this there will be a final PR to update the pipeline docker image.

Feat: implement pipeline

---

.travis.yml
.travis/travis-deploy.sh

we force deploying a new docker image for "pipeline"

hotfix to fix CI

---

repairnator/kubernetes-support/README.md
repairnator/kubernetes-support/queue-for-buildids/activemq.yaml
repairnator/kubernetes-support/repairnator-deployment-yamlfiles/repairnator-pipeline.yaml
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java

@monperrus Hi Martin :) , the pipeline is now on our cluster . I ran it together with build rainer and manual injection into ActiveMQ and found some improvements to be made. 
Instead of `System.exit(-1)` , which crash our K8s pipeline, we can return a boolean instead. WDYT ? 
PS: K8s does provide an auto crash recovery but It's better we spend it on real crashes instead of the ones we can handle like this one.

Fix: update pipeline K8s yamlfile

---

repairnator/README.md

and remove the broken link identified by @gustavopinto

doc: update sub README.md

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/astor/AstorRepair.java

This commit fixes #973

---

repairnator/repairnator-realtime/pom.xml
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerCollector.java
repairnator/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerLearnerScanner.java
repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestSequencerCollector.java
repairnator/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/utils/PatchFilterTest.java

Functionality to write diff files containing one-line-fixes into an external repository.
Currently using [repairnator/continuous-learning-data](https://github.com/repairnator/continuous-learning-data)

feat: write collected diff files to external repository

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/notifier/PatchNotifierImpl.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/JenkinsLauncher.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java

Issue (#469)
Hi @monperrus :) , This is a introduce a new entry point for the pipeline to be used by Jenkins plugin . It skip JSAP since it causes some errors and we don't really need JSAP if we use the plugin. I need this released to Sonatype later so I can import it as a maven dependency for our plugin.

Feat: New class to start pipeline from Jenkins plugin

---

repairnator/pom.xml

We'll merge only if 3.2 correctly appears on Central https://search.maven.org/search?q=a:repairnator-core

chore: update pom for deploy on Maven Central + bump

---

repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/notifier/JenkinsPatchNotifierImpl.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/JenkinsLauncher.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/RepairToolsManager.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/JenkinsProjectInspector.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/properties/reproductionBuggyBuild/ProcessDurations.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/AbstractStep.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/JenkinsCloneRepository.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/CommitFiles.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/push/JenkinsPushProcessEnd.java
repairnator/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractRepairStep.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNPERepair.java
repairnator/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/repair/TestNPERepairSafe.java

Making a repairnator plugin for Jenkins - issue (#469)

feat: chore infrastructure for the Repairnator Jenkins plugin

---

.travis/travis-deploy.sh

fix: fix deployment script

---

doc/repairnator-github-app.md
repairnator/repairnator-github-app/Dockerfile

for #978 
Signed-off-by: Jian GU <jianguda@gmail.com>

infra: add Dockerfile for GitHub app

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/AbstractRepairStep.java

fix: also do pull-requests on pull-requests

---

doc/repairnator-kubernetes.md

commands to upgrade the pipeline if a new version of docker image is pushed to Dockerhub
Signed-off-by: Long Zhang <zhanglong3030@qq.com>

doc: how to upgrade the repairnator pipeline

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/GitRepositoryLauncher.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/JenkinsLauncher.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/LauncherAPI.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/LegacyLauncher.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/NoopListener.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/PipelineBuildListener.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipelineb/BranchLauncher.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipelineb/Launcher.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipeline.java

Abstracting the pipeline for (#1061)
The file diff is a bit unclear on `Launcher` due to many line deleted, therefore viewing the file directly is advised :) .

Refactor: branch by abstraction for Pipeline Launcher

---

.travis/travis-settings.xml
doc/repairnator-jenkins-plugin.md
src/repairnator-jenkins-plugin/pom.xml

Fix: Jenkins deploy fix

---

.travis.yml

Fixes https://github.com/eclipse/repairnator/issues/1076

Fixed deploy stage condition in travis .yml

---

doc/docker.md

Documented sequencer docker image.

doc: document Sequencer image in docker.md

---

src/maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/NPEFixMojo.java

doc: improve documentation of NPEFixMojo

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/dockerpool/DockerPoolManager.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/DockerPipelineRunner.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/RTScanner.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/ZeroScanner.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestZeroScanner.java

- RepairnatorZero: fix circular reference and handle out-of-memory error
- Renamed AlphaScanner to ZeroScanner

fix: fix docker pipeline runner circular reference and handle OOM error

---

.travis.yml
.travis/travis-run-with-core.sh
src/pom.xml
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipelineb/BranchLauncher.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipelineb/github/GithubDefineJSAPArgs.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipelineb/github/GithubInitConfig.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/Sorald.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipelineb/TestPipelinebGithubMode.java
src/repairnator-realtime/pom.xml

Signed-off-by: henry-lp <tailp@kth.se>

Feat: support more Sorald options

---

doc/repair-tools.md
src/repairnator-jenkins-plugin/src/main/java/io/jenkins/plugins/main/RepairnatorJarDownloader.java
src/repairnator-jenkins-plugin/src/main/java/io/jenkins/plugins/main/RepairnatorPostBuild.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/Launcher.java

After debugging locally, I updated some parts of the Jenkins and also added some additional documentation for Sorald.

fix: various updates for sorald integration

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/SequencerConfig.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/AstorDetectionStrategy.java
src/repairnator-realtime/pom.xml
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerCollector.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerLearnerScanner.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/ZeroScanner.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/utils/PatchFilter.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/utils/RawURLGenerator.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestSequencerCollector.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/utils/PatchFilterTest.java

Astor detection strategy 
- suspicious lines limit
- suspicious value threshold
Sequencer collector:
- Add context size config
Inspector:
- Add travis build ID to "_topush" path

fix: improves Sequencer

---

src/maven-repair/README.md
src/maven-repair/src/main/java/com/github/tdurieux/repair/maven/plugin/NPEFixMojo.java

feat: maven-repair with automatic trigger of NPEfix after detecting failures

---

doc/README.md

grammatical/typo changes
Signed-off-by: poojachandak <poojachandak002@gmail.com>

doc: fix typos in README.md

---

src/docker-images/pipeline-dockerimage/pipeline_launcher.sh
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/config/RepairnatorConfig.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/dockerpool/RunnablePipelineContainer.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/pipeline/LegacyLauncher.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/SequencerRepair.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/MavenPatchTester.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/JobHelperv2.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/utils/PatchFilter.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/scanner/Launcher.java

Support for: 
- multi-model SequencerRepair image
- travis-ci.com API

feat: add support for multi-model Sequencer repair

---

src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/LauncherUtils.java
src/repairnator-core/src/main/java/fr/inria/spirals/repairnator/utils/Utils.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipeline.java

There was a mistake in the last PR (#1163) which I, stupidly, didn't notice. 
This PR fixes it.

fix: fix jsap arg handling regression

---

doc/README.md

I'm not sure how much detail we should put here (e.g. name of storage account, name of table, web service details)

doc: improve the "Pull Request" feature documentation.

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/AbstractStep.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestAbstractStep.java

- Implements addNextSteps method
- Implements test for addNextSteps method
- Implements test for addNextStep method

feat: add addNextSteps method

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/InspectorFactory.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/ProjectInspector.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/inspectors/components/RunInspector4Maven.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/inspectors/TestProjectInspector4Maven.java
src/repairnator-pipeline/src/test/resources/projects/example1/pom.xml
src/repairnator-pipeline/src/test/resources/projects/example1/src/main/java/Coneflower.java
src/repairnator-pipeline/src/test/resources/projects/example1/src/test/java/ConeflowerTest.java

- Introduces RunInspector4Maven
- Test for RunInspector4Maven

feat: introduce class RunInspector4Maven

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfo/GatherTestInformation.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/NPERepair.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/NPERepairSafe.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/testinformation/FailureLocation.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestGatherTestInformation.java

- Refactor FailureLocation to separate failures from errors.
- Adapt (temporarily) NPERepair steps.

refactor: refactor FailureLocation

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/gatherinfo/GatherTestInformation.java
src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/process/step/TestGatherTestInformation.java

- Change error/failure message from basic message to detailed message.
- Update assertion due to message change.
Needs to be rebased after merging #1182

Refactor: gather more failure information

---

src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/notifier/GitRepositoryPatchNotifierImpl.java
src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/AstorDetectionStrategy.java

SequencerRepair: added logs in email notification, and force `mvn clean` before each patch test

fix: fix bugs in SequencerRepair found with R-Hero

---

src/repairnator-core/pom.xml

Bump jtravis to 2.7

---

src/repairnator-pipeline/src/test/java/fr/inria/spirals/repairnator/pipeline/TestPipeline.java

test: fix flaky test

---

src/docker-images/pipeline-dockerimage/pipeline_launcher.sh
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/DockerPipelineRunner.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/SequencerLearnerScanner.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/ZeroScanner.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/githubapi/commits/GithubAPICommitAdapter.java
src/repairnator-realtime/src/main/java/fr/inria/spirals/repairnator/realtime/githubapi/repositories/GithubAPIRepoAdapter.java
src/repairnator-realtime/src/test/java/fr/inria/spirals/repairnator/realtime/TestZeroScanner.java

- Zero scanner (R-Hero)
- update: Remove usage of Travis API and use GitHub scanner instead.
- GitHub scanner: 
- fix: use UTC timezone
- update: fetch commit data in parallel

refactor: ZeroScanner (R-Hero) does not use Travis API and uses GitHub scanner 

---

src/maven-repair/pom.xml

mirror of #1201, since I don't have permission to edit it

update pom of maven-repair for release deployment
